name: Gate
run-name: Gate ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_call:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: false
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  workflow_dispatch:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: false
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  push:
    branches:
      - main
      - release-*
    paths:
      - 'gate/**'
      - 'fiat/**'
      - 'kork/**'
      - '.github/workflows/gate.yml'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'gate/**'
      - 'fiat/**'
      - 'kork/**'
      - '.github/workflows/gate.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
      - uses: ./.github/actions/generic-build-publish
        with:
          project: gate
          gradle-cmd-opts: -PenableCrossCompilerPlugin=true
          publish: 'false'
          publish-containers: 'false'
          publish-debs: 'false'
          publish-npm: 'false'
          publish-halconfig: 'false'
          version-override: ${{ inputs.version-override }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
