name: Kayenta Integration Tests

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - release-*
    paths:
      - 'kayenta/**'
      - '.github/workflows/kayenta-integration-tests.yml'

  pull_request:
    paths:
      - 'kayenta/**'
      - '.github/workflows/kayenta-integration-tests.yml'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

permissions:
  contents: read

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tests:
          ['Management', 'Swagger']
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Gradle validation step
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run Integration Test
        run: |
          ./gradlew :kayenta:kayenta-integration-tests:test --tests ${{ matrix.tests }}Test

  provider-integration-tests:
    name: Provider Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        provider: ['Prometheus', 'Graphite']
        test: ['canaryAnalysisIsSuccessful', 'canaryAnalysisIsFailed']
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Gradle validation step
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run Provider Integration Test
        run: |
          ./gradlew :kayenta:kayenta-integration-tests:test --tests ${{ matrix.provider }}StandaloneCanaryAnalysisTest.${{ matrix.test }}
