name: Kork
run-name: Kork ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - release-*
      - "coveo/release-*"
    paths:
      - 'kork/**'
      - '.github/workflows/kork.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generic-build-publish
        with:
          project: kork
          publish: 'false'
          publish-containers: 'false'
          publish-debs: 'false'
          publish-halconfig: 'false'
          publish-npm: 'false'
          integration-test: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
