name: Update Monorepo
run-name: Update Monorepo (${{ inputs.remote-ref }})

on:
  workflow_dispatch:
    inputs:
      remote-ref:
        description: Remote ref to merge from (master, release-1.35.x, etc)
        default: master
      merge-with-ours:
        description: Merge with the --ours strategy
        type: boolean
        default: true

jobs:
  update-monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.remote-ref == 'master' && 'main' || inputs.remote-ref }}
          fetch-depth: 0

      - uses: ./.github/actions/update-monorepo
        with:
          remote-ref: ${{ inputs.remote-ref }}
          github-pat: ${{ secrets.SPINNAKERBOT_PERSONAL_ACCESS_TOKEN }}
